### ISSUE TITLE
solutionerers

### ISSUE THREAD

**Issue by kustomzone** [aredfox/screencapturer#1]
Mentioning anyone who might know the answer, or who might know an answerer.

(see readme)

@zeke @paulcbetts

**Comment by zeke** [comment]
To reach a wider audience of knowledgeable electron folks, I would suggest opening an issue on electron/electron and linking to this repo and its readme.

**Comment by kustomzone** [comment]
The screencapturing works but not with ```new Date()``` in the filename as it contains colons. (windoze)
If replace with a datestamp or a counter it saves them okay.

**Comment by aredfox** [comment]
@kustomzone true, I'll change it, but it is not the main "question" ofcourse. The essence is that from my perspective the renderer process is blocking another render process, which - according to my knowledge of electron - shouldn't happen, as they're seperate processes?

**Comment by aredfox** [comment]
@zeke I posted it on https://discuss.atom.io/t/electron-ui-browserwindow-freezes-my-main-ui-browserwindow/37197 
I'll try filing an issue on the electron repo, but IDK if it's an electron problem itself or my own misunderstanding of how to use it, see my comment above here.

**Comment by aredfox** [comment]
**TODO:** One possible solution is to experiment with [electron-remote](https://github.com/paulcbetts/electron-remote) (by @paulcbetts) - though it adds a dependency on the electron-remote project, but nevertheless worth the investigation. Will look into it this week.
Ref:
* https://medium.com/@ccnokes/deep-dive-into-electrons-main-and-renderer-processes-7a9599d5c9e2#.ata4otsd7

**Comment by aredfox** [comment]
Possible culprit is desktopCapturer.getSources().

**CULPRIT:** Found that the issue must be inside the codeblock of `getMainSource`, because when I cache that "source" result it doesn't freeze the whole of electron. Thus it must be that the filter method or getting the screen itself is causing the issue of the freeze.

```
function getMainSource(desktopCapturer, screen, done) {
    const options = {
        types: ['screen'], thumbnailSize: screen.getPrimaryDisplay().workAreaSize
    }
    desktopCapturer.getSources(options, (err, sources) => {
        if (err) return console.log('Cannot capture screen: ', err)

        const isMainSource = source => source.name === 'Entire screen' || source.name === 'Screen 1'
        done(sources.filter(isMainSource)[0])
    })
}
```

The solution though is **not** caching the result of getMainSource (aka the "source"), as it will result in the same image data each time of course. I verified that by writing to file as png, and indeed each screenshot then was the exact same, even though enough had changed on the desktop. **TODO:** Possible option is to setup a video stream and save an image from the stream?

**Comment by aredfox** [comment]
If you're wanting to capture screenshots cross platform, i'd advice using the approach below in stead of relying on the built in electron-api's. Not that they're not good, but they're not suited for taking screenshots every three seconds for example.

The solution for me was the npm-module [desktop-screenshot](https://www.npmjs.com/package/desktop-screenshot) - and a npm package called [hazardous](https://www.npmjs.com/package/hazardous), as this was needed on Windows & asar execution.

The code I ended up implementing was this - it might be a source of inspiration/example for your problem.


    /* ******************************************************************** */
    /* MODULE IMPORTS */
    import { remote, nativeImage } from 'electron';
    import path from 'path';
    import os from 'os';
    import { exec } from 'child_process';
    import moment from 'moment';
    import screenshot from 'desktop-screenshot';
    /* */
    /*/********************************************************************///
    
    /* ******************************************************************** */
    /* CLASS */
    export default class ScreenshotTaker {    
        constructor() {
            this.name = "ScreenshotTaker";        
        }
    
        start(cb) {
            const fileName = `cap_${moment().format('YYYYMMDD_HHmmss')}.png`;
            const destFolder = global.config.app('capture.screenshots');
            const outputPath = path.join(destFolder, fileName);        
            const platform = os.platform();
            if(platform === 'win32') {
                this.performWindowsCapture(cb, outputPath);
            }
            if(platform === 'darwin') {
                this.performMacOSCapture(cb, outputPath);
            }
            if(platform === 'linux') {
                this.performLinuxCapture(cb, outputPath);
            }
        }
    
        performLinuxCapture(cb, outputPath) {
            // debian
            exec(`import -window root "${outputPath}"`, (error, stdout, stderr) => {
                if(error) {
                    cb(error, null, outputPath);
                } else {
                    cb(null, stdout, outputPath);
                }
            });
        }
        performMacOSCapture(cb, outputPath) {
            this.performWindowsCapture(cb, outputPath);
        }
        performWindowsCapture(cb, outputPath) {
            require('hazardous');
            screenshot(outputPath, (err, complete) => {
                if(err) {
                    cb(err, null, outputPath);
                } else {
                    cb(null, complete, outputPath);
                }
            });
        }
    }
    /*/********************************************************************///
